/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../example/app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import9 from '../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import10 from '../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import11 from '../directives/googleplace.directive.ngfactory';
import * as import12 from '@angular/core/src/linker/element_ref';
import * as import13 from '@angular/forms/src/directives/default_value_accessor';
import * as import14 from '@angular/forms/src/directives/control_value_accessor';
import * as import15 from '@angular/forms/src/directives/ng_model';
import * as import16 from '@angular/forms/src/directives/ng_control';
import * as import17 from '@angular/forms/src/directives/ng_control_status';
import * as import18 from '../../directives/googleplace.directive';
export class Wrapper_AppComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AppComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.AppComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.AppComponent>;
  _AppComponent_0_3:Wrapper_AppComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent_Host0,renderType_AppComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'my-app',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AppComponent0(this.viewUtils,this,0,this._el_0);
    this._AppComponent_0_3 = new Wrapper_AppComponent();
    this.compView_0.create(this._AppComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._AppComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AppComponentNgFactory:import7.ComponentFactory<import0.AppComponent> = new import7.ComponentFactory<import0.AppComponent>('my-app',View_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = ([] as any[]);
var renderType_AppComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_AppComponent,{});
export class View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _text_0:any;
  _el_1:any;
  _DefaultValueAccessor_1_3:import8.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_1_4:any[];
  _NgModel_1_5:import9.Wrapper_NgModel;
  _NgControl_1_6:any;
  _NgControlStatus_1_7:import10.Wrapper_NgControlStatus;
  _GoogleplaceDirective_1_8:import11.Wrapper_GoogleplaceDirective;
  _text_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent0,renderType_AppComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n	Type Location :\n        ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'input',new import3.InlineArray4(4,'googleplace','','type','text'),(null as any));
    this._DefaultValueAccessor_1_3 = new import8.Wrapper_DefaultValueAccessor(this.renderer,new import12.ElementRef(this._el_1));
    this._NG_VALUE_ACCESSOR_1_4 = [this._DefaultValueAccessor_1_3.context];
    this._NgModel_1_5 = new import9.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_1_4);
    this._NgControl_1_6 = this._NgModel_1_5.context;
    this._NgControlStatus_1_7 = new import10.Wrapper_NgControlStatus(this._NgControl_1_6);
    this._GoogleplaceDirective_1_8 = new import11.Wrapper_GoogleplaceDirective(new import12.ElementRef(this._el_1),this._NgModel_1_5.context);
    this._text_2 = this.renderer.createText(parentRenderNode,'\n        ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_1,new import3.InlineArray8(8,'ngModelChange',(null as any),'setAddress',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_1));
    this._NgModel_1_5.subscribe(this,this.eventHandler(this.handleEvent_1),true);
    this._GoogleplaceDirective_1_8.subscribe(this,this.eventHandler(this.handleEvent_1),true);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.DefaultValueAccessor) && (1 === requestNodeIndex))) { return this._DefaultValueAccessor_1_3.context; }
    if (((token === import14.NG_VALUE_ACCESSOR) && (1 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_1_4; }
    if (((token === import15.NgModel) && (1 === requestNodeIndex))) { return this._NgModel_1_5.context; }
    if (((token === import16.NgControl) && (1 === requestNodeIndex))) { return this._NgControl_1_6; }
    if (((token === import17.NgControlStatus) && (1 === requestNodeIndex))) { return this._NgControlStatus_1_7.context; }
    if (((token === import18.GoogleplaceDirective) && (1 === requestNodeIndex))) { return this._GoogleplaceDirective_1_8.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DefaultValueAccessor_1_3.ngDoCheck(this,this._el_1,throwOnChange);
    const currVal_1_1_0:any = this.context.address;
    this._NgModel_1_5.check_model(currVal_1_1_0,throwOnChange,false);
    this._NgModel_1_5.ngDoCheck(this,this._el_1,throwOnChange);
    this._NgControlStatus_1_7.ngDoCheck(this,this._el_1,throwOnChange);
    this._GoogleplaceDirective_1_8.ngDoCheck(this,this._el_1,throwOnChange);
    this._NgControlStatus_1_7.checkHost(this,this,this._el_1,throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_1_5.ngOnDestroy();
    this._GoogleplaceDirective_1_8.ngOnDestroy();
  }
  handleEvent_1(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_1_3.handleEvent(eventName,$event) && result);
    result = (this._GoogleplaceDirective_1_8.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.address = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'setAddress')) {
      const pd_sub_1:any = ((<any>this.context.getAddress($event)) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
}